server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /static/ {
        try_files $uri =404;
    }

    location ^~ /embed-runtime/ {
        try_files $uri $uri/ /embed-runtime/index.html;
    }

    location ^~ /embed/ {
        try_files $uri $uri/ /embed/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}